
defaults:
  - musdb18_hq

data_dir: ${oc.env:data_dir}

has_split_structure: True

validation_set:
#  - Meaxic - Take A Step
#  - Skelpolu - Human Mistakes
  - Actions - One Minute Smile
  - Clara Berry And Wooldog - Waltz For My Victims
  - Johnny Lokke - Promises & Lies
  - Patrick Talbot - A Reason To Leave
  - Triviul - Angelsaint
  - Alexander Ross - Goodbye Bolero
  - Fergessen - Nos Palpitants
  - Leaf - Summerghost
  - Skelpolu - Human Mistakes
  - Young Griffo - Pennies
  - ANiMAL - Rockshow
  - James May - On The Line
  - Meaxic - Take A Step
  - Traffic Experiment - Sirens


mode: musdb18hq