# output paths for hydra logs
run:
#  dir: logs/runs/${datamodule.target_name}_${exp_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  dir: ${get_train_log_dir:${datamodule.target_name},${exp_name}}

sweep:
#  dir: logs/multiruns/${now:%Y-%m-%d_%H-%M-%S}
  dir: ${get_sweep_log_dir:${datamodule.target_name},${exp_name}}
  subdir: ${hydra.job.num}

# you can set here environment variables that are universal for all users
# for system specific variables (like data paths) it's better to use .env file!
job:
  env_set:
    EXAMPLE_VAR: "example_value"

